#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck disable=SC2154
if [[ ${VPN_SOLUTION} == "wireguard" && ${1} == "down" ]]; then
  wg-quick down /etc/wireguard/wg0.conf
fi

if [[ ${VPN_SOLUTION} == "wireguard" && ${1} == "up" ]]; then
  wg-quick up /etc/wireguard/wg0.conf
fi

