#!/command/with-contenv bash
# shellcheck shell=bash

# if using wireguard shutdown openvpn
if [[ ${VPN_SOLUTION} == "wireguard" ]]; then
  /command/s6-svc -d /run/service/openvpn
fi

# shellcheck disable=SC2086
exec s6-setuidgid root \
  openvpn ${OPENVPN_OPTS} --config "${CHOSEN_OPENVPN_CONFIG}"
