#!/command/with-contenv bash
# shellcheck shell=bash

# if using wireguard shutdown openvpn
if [[ ${VPN_SOLUTION} == "wireguard" ]]; then
  /command/s6-svc -d /run/service/openvpn
fi

OPENVPN_OPTS='--script-security 2 --route-up /etc/openvpn/update-resolv-conf --route-pre-down /etc/openvpn/update-resolv-conf'
OPENVPN_OPTS+="${OPENVPN_OPTS}"

# shellcheck disable=SC2086
exec s6-setuidgid root \
  openvpn ${OPENVPN_OPTS} --config "${CHOSEN_OPENVPN_CONFIG}"
