---
# https://prettier.io/docs/en/options.html
# https://github.com/prettier/plugin-ruby
# https://github.com/rx-ts/prettier/tree/master/packages/sh

singleQuote: true
quoteProps: as-needed
tabWidth: 2
