---
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  document-start: enable
  line-length: disable
  truthy: { allowed-values: ['false', 'true', 'on', 'off'] }
  quoted-strings:
    quote-type: single
    required: only-when-needed
