---
# some helpful links to help me remember stuff
# https://squidfunk.github.io/mkdocs-material/setup/extensions/
# https://python-markdown.github.io/extensions/
# https://docutils.sourceforge.io/docs/ref/rst/directives.html#specific-admonitions

site_name: docker-openvpn-client
site_url: http://jsloan117.github.io/docker-openvpn-client
repo_url: https://github.com/jsloan117/docker-openvpn-client

theme:
  name: "material"

markdown_extensions:
  admonition: {}
  codehilite:
    linenums: true
  toc:
    permalink: true
    separator: "_"

nav:
  - "Home": "index.md"
  - "Run from Docker registry": "run-from-docker-registry.md"
  - "Configuration": "configuration.md"
  - "Supported providers": "supported-providers.md"

plugins:
  minify:
    minify_html: true
  search: {}
