#!/command/with-contenv bash
# shellcheck shell=bash

if [[ ${VPN_SOLUTION} == "openvpn" ]]; then
  /etc/scripts/setup.sh
fi

# bring service down
# /command/s6-svc -d /run/service/openvpn
# handles deps
# /command/s6-rc -d|-u change openvpn

# s6-rc: fatal: unable to take locks: Resource busy
# Options error: In [CMD-LINE]:1: Error opening configuration file:

