#!/command/with-contenv bash
# shellcheck shell=bash

if [[ ${VPN_SOLUTION} == "wireguard" ]]; then
  #/command/s6-rc -d change openvpn
  /command/s6-svc -d /run/service/openvpn
fi

if [[ ${VPN_SOLUTION} == "openvpn" ]]; then
  /etc/scripts/setup.sh
fi

# bring service down
# /command/s6-svc -d /run/service/openvpn
# handles deps
# /command/s6-rc -d|-u change openvpn
