#!/command/with-contenv bash
# shellcheck shell=bash

# ensure we run the update-resolv-conf script to prevent leaking DNS
# RESOLV_OPTS='--script-security 2 --route-up /etc/openvpn/update-resolv-conf --down /etc/openvpn/update-resolv-conf'
# openvpn ${RESOLV_OPTS} ${OPENVPN_OPTS} --config "${CHOSEN_OPENVPN_CONFIG}"

# shellcheck disable=SC2086,SC2154
exec \
  s6-notifyoncheck -d -s 3000 -n 120 -w 1000 \
  s6-setuidgid root openvpn ${OPENVPN_OPTS} --config "${CHOSEN_OPENVPN_CONFIG}"

