---
name: Delete Untagged Container Images

on:
  schedule:
    - cron: '0 0 1 * *' # yamllint disable-line rule:quoted-strings

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      # https://github.com/marketplace/actions/delete-untagged
      - name: Delete Untagged
        uses: Chizkiyahu/delete-untagged-ghcr-action@v4
        with:
          token: ${{ secrets.PKG_CLEANUP_KEY }}
          owner_type: user
          repository: ${{ github.repository }}
          repository_owner: ${{ github.repository_owner }}
          untagged_only: true
          except_untagged_multiplatform: true

