---
name: delete untagged

on:
  schedule:
    - cron: '5 0 * * *' # yamllint disable-line rule:quoted-strings
  workflow_dispatch:

permissions: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/delete-untagged
      - name: Delete Untagged
        # uses: camargo/delete-untagged-action@v1
        uses: jsloan117/delete-untagged-action@v1.0.1
        with:
          github-token: ${{ secrets.PKG_CLEANUP }}
          personal-account: true
