---
name: Pull Request Labeler

on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/labeler
      - name: Label PRs
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
