---
name: mkdocs

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "**.md"
      - "mkdocs.yml"
      - .github/workflows/mkdocs.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2.4.0

      # https://github.com/marketplace/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.9"

      - run: pip install wheel

      - name: Install MkDocs and deps
        run: |
          pip install mkdocs mkdocs-material mkdocs-material-extensions \
          mkdocs-minify-plugin mkdocs-redirects pygments pymdown-extensions

      - name: Build docs
        run: mkdocs build -vcs

      # https://github.com/marketplace/actions/import-gpg
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          fingerprint: B4AAB0C18DF55304
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"

      # https://github.com/marketplace/actions/github-pages-action
      - name: Deploy
        if: success() && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          force_orphan: true
          full_commit_message: "Deployed ${{ github.sha }} to gh-pages [skip ci]"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-dev
          publish_dir: ./site

      # https://github.com/marketplace/actions/github-pages
      # - name: GitHub Pages
      #   if: success()
      #   # if: success() && ${{ github.ref == 'refs/heads/main' }} && github.event_name != 'pull_request'
      #   uses: crazy-max/ghaction-github-pages@v2.5.0
      #   with:
      #     author: jsloan117@users.noreply.github.com
      #     committer: jsloan117
      #     build_dir: ./site
      #     commit_message: "Deployed ${{ github.sha }} to gh-pages [skip ci]"
      #     jekyll: false
      #     target_branch: gh-pages-dev
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
