---
name: docs

on:
  push:
    branches:
      - dev
    paths:
      - '**.md'
      - mkdocs.yml
      - .github/workflows/mkdocs.yml

workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: pip install wheel

      - name: Install MkDocs and deps
        run: |
          pip install mkdocs mkdocs-material mkdocs-material-extensions \
          mkdocs-minify-plugin mkdocs-redirects pygments pymdown-extensions

      - name: Build docs
        run: mkdocs build -vcs

      # https://github.com/marketplace/actions/upload-github-pages-artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site
          retention-days: 1

      # # https://github.com/marketplace/actions/github-pages-action
      # - name: Upload to gh-pages
      #   if: success() && github.event_name != 'pull_request'
      #   uses: peaceiris/actions-gh-pages@v3.9.0
      #   with:
      #     force_orphan: true
      #     full_commit_message: Deployed ${{ github.sha }} to gh-pages [skip ci]
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_branch: gh-pages
      #     publish_dir: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

