---
name: Tag and Release

on:
  push:
    branches:
      - main
    paths:
      - etc/**
      - openvpn/**
      - scripts/**
      - Dockerfile
      - Dockerfile.*

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2.4.0

      # https://github.com/marketplace/actions/github-tag
      # https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          default_bump: patch
          github_token: ${{ secrets.GH_PAT }}
          tag_prefix: v

      # https://github.com/marketplace/actions/create-release
      # https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
